# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.SmallIntegerField(choices=[(1, 'Tall'), (2, 'Normal'), (3, 'Short')])),
                ('description', models.TextField(blank=True)),
                ('is_quiet', models.BooleanField()),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='KitchenSink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('help_text', models.CharField(help_text='Enter fully qualified name', max_length=64)),
                ('multiple_in_row', models.CharField(help_text='Help text for multiple', max_length=64)),
                ('multiple2', models.CharField(blank=True, max_length=10)),
                ('textfield', models.TextField(blank=True, help_text='Try and enter few some more lines', verbose_name='Autosized textarea')),
                ('file', models.FileField(blank=True, upload_to='.')),
                ('readonly_field', models.CharField(default='Some value here', max_length=127)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_and_time', models.DateTimeField(blank=True, null=True)),
                ('date_widget', models.DateField(blank=True, null=True)),
                ('datetime_widget', models.DateTimeField(blank=True, null=True)),
                ('boolean', models.BooleanField(default=True)),
                ('boolean_with_help', models.BooleanField(help_text='Boolean field with help text')),
                ('horizontal_choices', models.SmallIntegerField(choices=[(1, 'Awesome'), (2, 'Good'), (3, 'Normal'), (4, 'Bad')], default=1, help_text='Horizontal choices look like this')),
                ('vertical_choices', models.SmallIntegerField(choices=[(1, 'Hot'), (2, 'Normal'), (3, 'Cold')], default=2, help_text='Some help on vertical choices')),
                ('choices', models.SmallIntegerField(choices=[(1, 'Tall'), (2, 'Normal'), (3, 'Short')], default=3, help_text='Help text')),
                ('hidden_checkbox', models.BooleanField()),
                ('hidden_choice', models.SmallIntegerField(blank=True, choices=[(1, 'Tall'), (2, 'Normal'), (3, 'Short')], default=2)),
                ('hidden_charfield', models.CharField(blank=True, max_length=64)),
                ('hidden_charfield2', models.CharField(blank=True, max_length=64)),
                ('enclosed1', models.CharField(blank=True, max_length=64)),
                ('enclosed2', models.CharField(blank=True, max_length=64)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_key_country', to='world.Country')),
                ('linked_foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_key_linked', to='world.Country')),
                ('raw_id_field', models.ForeignKey(blank=True, help_text='Regular raw ID field', null=True, on_delete=django.db.models.deletion.CASCADE, to='world.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Microwave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.SmallIntegerField(choices=[(1, 'Tall'), (2, 'Normal'), (3, 'Short')], default=2, help_text='Choose wisely')),
                ('is_compact', models.BooleanField()),
                ('order', models.PositiveIntegerField()),
                ('kitchensink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.KitchenSink')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='fridge',
            name='kitchensink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.KitchenSink'),
        ),
    ]
